import type { NextPage } from 'next';
import { useTheme } from 'next-themes';
import Head from 'next/head';
import Image from 'next/image';
import { styled } from '../stitches';

const Container = styled('div', {
  paddingInline: '2rem',
});

const Main = styled('main', {
  minHeight: '100vh',
  paddingBlock: '4rem',

  flex: '1',

  display: 'flex',
  flexDirection: 'column',
  justifyContent: 'center',
  alignItems: 'center',
});

const Footer = styled('footer', {
  paddingBlock: '2rem',

  borderTop: '1px solid $slate6',

  flex: '1',

  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',

  '& a': {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexGrow: '1',
  },
});

const Button = styled('button', {
  cursor: 'pointer',

  background: '$slate3',

  padding: '0.75rem',
  marginBottom: '2rem',

  border: '1px solid transparent',
  borderRadius: 5,
  outline: 'none',

  fontSize: '1.1rem',
  fontWeight: 'bold',
  fontFamily:
    'Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace',

  '&:hover, &:focus': {
    background: '$slate4',
  },

  '&:active': {
    background: '$slate5',
  },
});

const Title = styled('h1', {
  margin: '0',

  textAlign: 'center',
  lineHeight: '1.15',
  fontSize: '4rem',

  '& a': {
    color: '$blue9',
    textDecoration: 'none',

    '&:hover, &:focus, &:active': {
      color: '$blue10',
      textDecoration: 'underline',
    },
  },
});

const Description = styled('p', {
  marginBlock: '4rem',

  textAlign: 'center',
  lineHeight: '1.5',
  fontSize: '1.5rem',

  '& code': {
    background: '$slate3',
    padding: '0.75rem',

    borderRadius: 5,

    fontSize: '1.1rem',
    fontFamily:
      'Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace',
  },
});

const Grid = styled('div', {
  maxWidth: 800,

  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  flexWrap: 'wrap',

  '@bp': {
    width: '100%',

    flexDirection: 'column',
  },
});

const Card = styled('a', {
  maxWidth: 300,

  margin: '1rem',
  padding: '1.5rem',

  border: '1px solid $slate7',
  borderRadius: 10,

  textAlign: 'left',
  color: 'inherit',
  textDecoration: 'none',

  '&:hover, &:focus, &:active': {
    color: '$blue9',
    borderColor: '$blue9',
  },

  '& h2': {
    marginBottom: '1rem',

    fontSize: '1.5rem',
  },

  '& p': { margin: '0', fontSize: '1.25rem', lineHeight: '1.5' },
});

const Logo = styled('span', {
  height: '1em',

  marginLeft: '0.5rem',
});

const Home: NextPage = () => {
  const { theme, setTheme } = useTheme();  

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <Button onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')}>switch theme</Button>

        <Title>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Title>

        <Description>
          Get started by editing <code>pages/index.tsx</code>
        </Description>

        <Grid>
          <Card href="https://nextjs.org/docs">
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </Card>

          <Card href="https://nextjs.org/learn">
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </Card>

          <Card href="https://github.com/vercel/next.js/tree/canary/examples">
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </Card>

          <Card href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app">
            <h2>Deploy &rarr;</h2>
            <p>Instantly deploy your Next.js site to a public URL with Vercel.</p>
          </Card>
        </Grid>
      </Main>

      <Footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <Logo>
            <Image
              src="/vercel.svg"
              alt="Vercel Logo"
              style={{
                filter: theme && theme === 'dark' ? 'invert(1)' : 'none',
              }}
              width={72}
              height={16}
            />
          </Logo>
        </a>
      </Footer>
    </Container>
  );
};

export default Home;
